enum ActionType {
  SIGN_IN_PENDING,
  SIGN_IN_SUCCESS,
  SIGN_IN_ERROR,
  SIGN_OUT_PENDING,
  SIGN_OUT_SUCCESS,
  SIGN_OUT_ERROR,
  CHECK_AUTHENTICATION_PENDING,
  CHECK_AUTHENTICATION_PENDING_TOO_LONG,
  CHANGE_LOCALE
}

export default ActionType;
